name: C/C++ CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "SiliconLabs/gecko_sdk"
        tag: "v4.3.1"
        fileName: "gecko-sdk.zip"
        out-file-path: /Users/ltarantino/SimplicityStudio/SDKs/gecko_sdk_3/
        extract: true  
#    - name: configure
#      run: ./configure
    - name: make
      run: make -f rcp-uart-802154_2.Makefile release
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
    - name: create gbl
      run: commander gbl create  "./build/release/rcp-uart-802154_2.gbl" --app "./build/release/rcp-uart-802154_2.s37" 
