name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
#  pull_request:
#    branches: [ "main" ]

env:
  GECKO_VERSION: "4.3.1"
  COMMANDER_VERSION: "1v15p3b1357"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Download And Install Simplicity Commander"
        run: |
          wget https://www.silabs.com/documents/login/software/SimplicityCommander-Linux.zip
          unzip SimplicityCommander-Linux.zip
          tar xvf SimplicityCommander-Linux/Commander_linux_x86_64_${COMMANDER_VERSION}.tar.bz
      - uses: robinraju/release-downloader@v1.8
        name: Download GeckoSDK
        with:
          repository: "SiliconLabs/gecko_sdk"
          tag: "v${{env.GECKO_VERSION}}"
          fileName: "gecko-sdk.zip"
          out-file-path: ./gecko_sdk_${{env.GECKO_VERSION}}
          extract: true
      - name: Install Arm Toolchain
        id: arm
        uses: turtlesec-no/get-arm-toolchain@main
      - name: Arm Toolchain version
        run: echo "${{ steps.arm.outputs.version }}"
      - name: make
        run: BASE_SDK_PATH=./gecko_sdk_${GECKO_VERSION} make -f rcp-uart-802154_2.Makefile release
      - name: create gbl
        run: ./commander/commander gbl create  "./build/release/rcp-uart-802154_2.gbl" --app "./build/release/rcp-uart-802154_2.s37"
      - uses: actions/upload-artifact@v3
        with:
          name: Firmwares
          path: build/release/rcp-uart-802154* # or path/to/artifact
      - name: Recreate Release ${{env.GECKO_VERSION}}
        uses: GongT/actions-recreate-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.GECKO_VERSION}}
          release_name: Release at ${{ github.ref }}
          body: |
            Changes in this Release
            - Bump Gecko SDK version ${{env.GECKO_VERSION}}
          draft: false
          prerelease: false
      - name: Upload Firmware (GBL) to release ${{env.GECKO_VERSION}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rcp-uart-802154.gbl
          asset_content_type: application/binary
          asset_path: build/release/rcp-uart-802154_2.gbl
          upload_url: ${{steps.release.outputs.upload_url}}
      - name: Upload Firmware (BIN) to release ${{env.GECKO_VERSION}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rcp-uart-802154.bin
          asset_content_type: application/binary
          asset_path: build/release/rcp-uart-802154_2.bin
          upload_url: ${{steps.release.outputs.upload_url}}
      - name: Upload Firmware (S37) to release ${{env.GECKO_VERSION}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rcp-uart-802154.s37
          asset_content_type: application/binary
          asset_path: build/release/rcp-uart-802154_2.s37
          upload_url: ${{steps.release.outputs.upload_url}}
      - name: Upload Firmware (HEX) to release ${{env.GECKO_VERSION}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rcp-uart-802154.hex
          asset_content_type: application/binary
          asset_path: build/release/rcp-uart-802154_2.hex
          upload_url: ${{steps.release.outputs.upload_url}}
