name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Download And Install Simplicity Commander"
        run: |
          wget https://www.silabs.com/documents/login/software/SimplicityCommander-Linux.zip
          unzip SimplicityCommander-Linux.zip
          tar xvf SimplicityCommander-Linux/Commander_linux_x86_64_1v15p3b1357.tar.bz
      - uses: robinraju/release-downloader@v1.8
        name: Download GeckoSDK
        with:
          repository: "SiliconLabs/gecko_sdk"
          tag: "v4.3.1"
          fileName: "gecko-sdk.zip"
          out-file-path: ./gecko_sdk_4.3.1
          extract: true
      - name: Install Arm Toolchain
        id: arm
        uses: turtlesec-no/get-arm-toolchain@main
      - name: Arm Toolchain version
        run: echo "${{ steps.arm.outputs.version }}"
      - name: make
        run: BASE_SDK_PATH=./gecko_sdk_4.3.1 make -f rcp-uart-802154_2.Makefile release
      - name: create gbl
        run: ./commander/commander gbl create  "./build/release/rcp-uart-802154_2.gbl" --app "./build/release/rcp-uart-802154_2.s37"
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/release/ # or path/to/artifact
